version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=root
      - DB_PASS=rootdevdb
      - DEBUG=1
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - dev-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootdevdb
      - MYSQL_DATABASE=devdb
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=changeme
    ports:
      - "3306:3306"

volumes:
  dev-db-data:
  dev-static-data:
