# Generated by Django 4.1.7 on 2023-03-26 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_character_created_at_character_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=portfolio.models.artist_image_file_path)),
                ('instagram', models.CharField(blank=True, max_length=128, null=True)),
                ('deviant', models.CharField(blank=True, max_length=128, null=True)),
                ('twitter', models.CharField(blank=True, max_length=128, null=True)),
                ('oficial', models.CharField(blank=True, max_length=128, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
