# Generated by Django 4.1.7 on 2023-03-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='characters',
            field=models.ManyToManyField(blank=True, to='portfolio.character'),
        ),
        migrations.AlterField(
            model_name='art',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolio.tag'),
        ),
    ]
