# Generated by Django 4.2 on 2023-06-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_art_characters_alter_art_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
